development:
  adapter: sqlite3
  encoding: utf8
  database: startup_discovery_dev

test:
  adapter: sqlite3
  encoding: utf8
  database: startup_discovery_test

production:
  adapter: sqlite3
  encoding: unicode
  database: startup_discovery_production